baseURL = 'https://gees.dev/'
languageCode = 'en-us'
title = 'Personal Website Of Mattias Gees'
theme = 'typo'

[taxonomies]
tag = 'tags'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[params]
# Meta description
description = "A Tech Blog"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """
I’m a Belgian based in London, working as a Director of Technology at CyberArk with a focus on Workload Identity, SPIFFE, and SPIRE.
My interests span a wide range of topics, including Software Engineering, Kubernetes, Cloud-Native technologies, Software Supply Chain Security, and Workload Identity.
"""

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 10
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/MattiasGees/"

[[params.social]]
name = "github"
url = "https://github.com/MattiasGees"

[[params.social]]
name = "bluesky"
url = "https://bsky.app/profile/mattiasgees.bsky.social"


# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "talks"
url = "/talks"

[[params.menu]]
name = "about"
url = "/about"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"
